; Modem模拟器的设置
[Setup]
; Server表示设备Modem，Remote表示PC/前端机
ServerIp_Orig=192.168.0.70
ServerPort=1104
ModemIp_Orig=192.168.0.89
ModemPort=1234

CClWaveType=0
ChargeVoltWaveType=1
CclAmplitude=2000
CclFreq=1
ChargeVoltAmplitude=2000
ChargeVoltFreq=1

ServerIp=127.0.0.1
ModemIp=127.0.0.1
PauseDisplay=0
IpSelect=0
